# Generated by Django 4.1.5 on 2023-01-11 10:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview', models.ImageField(default='default2.jpg', upload_to='categorie_images')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Pas de description')),
            ],
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(default='Pas de description')),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('preview', models.ImageField(default='default.jpg', upload_to='event_images')),
                ('type', models.CharField(choices=[('PUBLIC', 'PUBLIC'), ('PRIVE', 'PRIVE')], default='PRIVE', max_length=100)),
                ('code_adhesion', models.CharField(default='', max_length=20)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('start_date', models.DateTimeField(verbose_name="Date de debut de l'évenement")),
                ('end_date_inscription', models.DateTimeField(verbose_name="Date cloture de l'inscription")),
                ('location', models.CharField(default='En ligne', max_length=255)),
                ('number_phone', models.CharField(max_length=20)),
                ('latitude', models.FloatField(default=0.0)),
                ('longitude', models.FloatField(default=0.0)),
                ('is_active', models.BooleanField(default=True)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.categorie')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
