# Generated by Django 4.1.5 on 2023-01-11 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='categorie',
            new_name='category',
        ),
    ]
