# Generated by Django 4.1.5 on 2023-01-13 15:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_alter_event_start_date_guest_event_guests'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 6, 25, 717580, tzinfo=datetime.timezone.utc), verbose_name="Date de fin de l'evenement"),
        ),
        migrations.AddField(
            model_name='guest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guest',
            name='feedback',
            field=models.TextField(default="Je n'ai pas participé à l'evenement"),
        ),
        migrations.AddField(
            model_name='guest',
            name='rating',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 1, 13, 16, 6, 25, 717580), verbose_name="Date de debut de l'évenement"),
        ),
    ]
