# Generated by Django 4.1.5 on 2023-03-03 17:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_event_end_date_guest_created_at_guest_feedback_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 18, 9, 45, 454141, tzinfo=datetime.timezone.utc), verbose_name="Date de fin de l'evenement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 9, 9, 45, 454141), verbose_name="Date de debut de l'évenement"),
        ),
    ]
