# Generated by Django 4.1.5 on 2023-03-03 13:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_alter_event_end_date_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 14, 13, 26, 439954, tzinfo=datetime.timezone.utc), verbose_name="Date de fin de l'evenement"),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 3, 3, 5, 13, 26, 439954), verbose_name="Date de debut de l'évenement"),
        ),
    ]
